[project]
name = "weather_ab"
version = "1.0.0"
description = "Simple weather API and Telegram bot."
dependencies = [
    "Django",
    "requests",
]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "local_settings"

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"
